"""Initial migration with TodoItem.

Revision ID: b38fb0519c83
Revises:
Create Date: 2026-01-25 16:00:37.378831

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b38fb0519c83"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("todo_items",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(length=200), nullable=False),
    sa.Column("is_done", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todo_items_id"), "todo_items", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todo_items_id"), table_name="todo_items")
    op.drop_table("todo_items")
    # ### end Alembic commands ###
